name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run workflow tests
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/metapep') }}
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    strategy:
      fail-fast: false
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.0', '']
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            Dockerfile
            environment.yml

      - name: Build new docker image
        if: env.MATCHED_FILES
        run: docker build --no-cache . -t skrakau/metapep:dev

      - name: Pull docker image
        if: ${{ !env.MATCHED_FILES }}
        run: |
          docker pull skrakau/metapep:dev
          docker tag skrakau/metapep:dev skrakau/metapep:dev

      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        env:
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          NCBI_KEY: ${{ secrets.NCBI_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --ncbi_email "$NCBI_EMAIL" --ncbi_key "$NCBI_KEY"

  profile:
    name: Run additional profile tests
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/metapep') }}
    runs-on: ubuntu-latest
    env:
      NXF_VER: '20.04.0'
      NXF_ANSI_LOG: false
    strategy:
      fail-fast: false
      matrix:
        tests: ['test_mouse', 'test_assembly_only']   # add further test profiles here, will be run in parallel (but only with one nextflow version)
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            Dockerfile
            environment.yml

      - name: Build new docker image
        if: env.MATCHED_FILES
        run: docker build --no-cache . -t skrakau/metapep:dev

      - name: Pull docker image
        if: ${{ !env.MATCHED_FILES }}
        run: |
          docker pull skrakau/metapep:dev
          docker tag skrakau/metapep:dev skrakau/metapep:dev

      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with profile ${{ matrix.tests }}
        env:
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          NCBI_KEY: ${{ secrets.NCBI_KEY }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.tests }},docker --ncbi_email "$NCBI_EMAIL" --ncbi_key "$NCBI_KEY"
